# 这个会被所有应用读取到，用来做公共配置
spring:
  rabbitmq:
    host: 192.168.121.129
    username: guest
    # 密文需要以{cipher}做为标识
    password: '{cipher}e2898a193d92e8cfcbfe33c0db417853938c7ed2038a6b10cce2aece67be66cd'
info:
  name: lession-2-sms-interface
server:
  port: 9002

# 调用refresh的时候不校验权限
management:
  security:
    enabled: false
    
liyj:
  configString: Hello World shanshan!
